apiVersion: v1
kind: ConfigMap
metadata:
  name: "sample_project"
  labels:
    app: "sample_project.name"
    chart: "sample_project.chart"
data:
  {{- $root := . -}}
  {{- range $path, $bytes := .Files.Glob "files/*.json" }}
  {{ base $path }}: |-
{{ $root.Files.Get $path | indent 4}}
  {{- end }}
